# generated by datamodel-codegen:
#   filename:  email_received_event.schema.json

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel


class Delivery(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    endpoint_id: str = Field(
        ...,
        description='ID of the webhook endpoint receiving this event. Matches the endpoint ID from your Primitive dashboard.',
    )
    attempt: int = Field(
        ...,
        description='Delivery attempt number, starting at 1. Increments with each retry if previous attempts failed.',
        ge=1,
    )
    attempted_at: str = Field(
        ...,
        description='ISO 8601 timestamp (UTC) when this delivery was attempted.',
        examples=['2025-01-15T10:30:00.000Z'],
    )


class Smtp(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    helo: str | None = Field(
        ...,
        description='HELO/EHLO hostname from the sending server. Null if not provided during SMTP transaction.',
    )
    mail_from: str = Field(
        ...,
        description='SMTP envelope sender (MAIL FROM command). This is the bounce address, which may differ from the From header.',
    )
    rcpt_to: list[str] = Field(
        ...,
        description='SMTP envelope recipients (RCPT TO commands). All addresses that received this email in a single delivery.',
        min_length=1,
    )


class Headers(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    message_id: str | None = Field(
        ...,
        description='Message-ID header value. Null if the email had no Message-ID header.',
    )
    subject: str | None = Field(
        ...,
        description='Subject header value. Null if the email had no Subject header.',
    )
    from_: str = Field(
        ...,
        alias='from',
        description='From header value. May include display name: `"John Doe" <john@example.com>`',
    )
    to: str = Field(
        ...,
        description='To header value. May include multiple addresses or display names.',
    )
    date: str | None = Field(
        ...,
        description='Date header value as it appeared in the email. Null if the email had no Date header.',
    )


class Download(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    url: AnyUrl = Field(
        ...,
        description='HTTPS URL to download the raw email. Returns the email as-is in RFC 5322 format.',
    )
    expires_at: str = Field(
        ...,
        description='ISO 8601 timestamp (UTC) when this URL expires. Download before this time or the URL will return 403.',
    )


class WebhookVersion(RootModel[str]):
    root: str = Field(
        ...,
        description='Valid webhook version format (YYYY-MM-DD date string). The SDK accepts any valid date-formatted version, not just the current one, for forward and backward compatibility.',
        pattern='^\\d{4}-\\d{2}-\\d{2}$',
    )


class RawContentInline(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    included: Literal[True] = Field(
        ..., description='Discriminant indicating raw content is included inline.'
    )
    encoding: Literal['base64'] = Field(
        ..., description='Encoding used for the data field. Always "base64".'
    )
    max_inline_bytes: int = Field(
        ...,
        description='Maximum size in bytes for inline inclusion. Emails larger than this threshold require download.',
        ge=1,
    )
    size_bytes: int = Field(
        ..., description='Actual size of the raw email in bytes.', ge=0
    )
    sha256: str = Field(
        ...,
        description='SHA-256 hash of the raw email content (hex-encoded). Use this to verify integrity after base64 decoding.',
        pattern='^[a-fA-F0-9]{64}$',
    )
    data: str = Field(
        ...,
        description="Base64-encoded raw email (RFC 5322 format). Decode with `Buffer.from(data, 'base64')` in Node.js.",
    )


class RawContentDownloadOnly(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    included: Literal[False] = Field(
        ..., description='Discriminant indicating raw content must be downloaded.'
    )
    reason_code: Literal['size_exceeded'] = Field(
        ..., description="Reason the content wasn't included inline."
    )
    max_inline_bytes: int = Field(
        ...,
        description='Maximum size in bytes for inline inclusion. The email exceeded this threshold.',
        ge=1,
    )
    size_bytes: int = Field(
        ..., description='Actual size of the raw email in bytes.', ge=0
    )
    sha256: str = Field(
        ...,
        description='SHA-256 hash of the raw email content (hex-encoded). Use this to verify integrity after download.',
        pattern='^[a-fA-F0-9]{64}$',
    )


class EmailAddress(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    address: str = Field(
        ...,
        description='The email address portion (e.g., "john@example.com").\n\nThis is the raw value from the email header with no validation applied. May contain unusual but valid formats like quoted local parts.',
    )
    name: str | None = Field(
        ...,
        description='The display name portion, if present. Null if the address had no display name.\n\nMay contain any characters including unicode, emoji, or special characters as they appeared in the original email header.',
    )


class WebhookAttachment(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    filename: str | None = Field(
        ...,
        description='Original filename from the email. May be null if the attachment had no filename specified.',
    )
    content_type: str = Field(
        ..., description='MIME content type (e.g., "application/pdf", "image/png").'
    )
    size_bytes: int = Field(..., description='Size of the attachment in bytes.', ge=0)
    sha256: str = Field(
        ...,
        description='SHA-256 hash of the attachment content (hex-encoded). Use this to verify attachment integrity after download.',
        pattern='^[a-fA-F0-9]{64}$',
    )
    part_index: int = Field(
        ..., description='Zero-based index of this part in the MIME structure.', ge=0
    )
    tar_path: str = Field(
        ..., description='Path to this attachment within the downloaded tar.gz archive.'
    )


class Code(StrEnum):
    parse_failed = 'PARSE_FAILED'
    attachment_extraction_failed = 'ATTACHMENT_EXTRACTION_FAILED'


class ParsedError(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    code: Code = Field(
        ...,
        description="Error code indicating the type of failure.\n- `PARSE_FAILED`: The email could not be parsed (e.g., malformed MIME)\n- `ATTACHMENT_EXTRACTION_FAILED`: Email parsed but attachments couldn't be extracted",
    )
    message: str = Field(
        ..., description='Human-readable error message describing what went wrong.'
    )
    retryable: bool = Field(
        ...,
        description='Whether retrying might succeed. If true, the error was transient (e.g., timeout). If false, the email itself is problematic.',
    )


class Spamassassin(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    score: float = Field(
        ...,
        description='Overall spam score (sum of all rule scores). Higher scores indicate higher likelihood of spam. Unbounded - can be negative (ham) or very high (spam).',
    )


class ForwardOriginalSender(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    email: str = Field(..., description='Email address of the original sender.')
    domain: str = Field(..., description='Domain of the original sender.')


class ForwardVerdict(StrEnum):
    legit = 'legit'
    unknown = 'unknown'


class AuthConfidence(StrEnum):
    high = 'high'
    medium = 'medium'
    low = 'low'


class DmarcPolicy(Enum):
    reject = 'reject'
    quarantine = 'quarantine'
    none = 'none'
    none_type_none = None


class ForwardResultAttachmentSkipped(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['attachment']
    attachment_tar_path: str = Field(
        ..., description='Path to the attachment in the attachments tar archive.'
    )
    attachment_filename: str | None = Field(
        ..., description='Original filename of the attachment, if available.'
    )
    analyzed: Literal[False] = Field(
        ..., description='Whether this attachment was analyzed.'
    )
    original_sender: None = Field(..., description='Always null when not analyzed.')
    verification: None = Field(..., description='Always null when not analyzed.')
    summary: str = Field(
        ..., description='Human-readable summary explaining why analysis was skipped.'
    )


class SpfResult(StrEnum):
    pass_ = 'pass'
    fail = 'fail'
    softfail = 'softfail'
    neutral = 'neutral'
    none = 'none'
    temperror = 'temperror'
    permerror = 'permerror'


class DmarcResult(StrEnum):
    pass_ = 'pass'
    fail = 'fail'
    none = 'none'
    temperror = 'temperror'
    permerror = 'permerror'


class DkimResult(StrEnum):
    pass_ = 'pass'
    fail = 'fail'
    temperror = 'temperror'
    permerror = 'permerror'


class RawContent(RootModel[RawContentInline | RawContentDownloadOnly]):
    root: RawContentInline | RawContentDownloadOnly = Field(
        ..., description='Raw email content - a discriminated union on `included`.'
    )


class ParsedDataComplete(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    status: Literal['complete'] = Field(
        ..., description='Discriminant indicating successful parsing.'
    )
    error: None = Field(..., description='Always null when parsing succeeds.')
    body_text: str | None = Field(
        ...,
        description='Plain text body of the email. Null if the email had no text/plain part.',
    )
    body_html: str | None = Field(
        ...,
        description='HTML body of the email (sanitized via DOMPurify). Null if the email had no text/html part.',
    )
    reply_to: list[EmailAddress] | None = Field(
        ...,
        description='Parsed Reply-To header addresses. Null if the email had no Reply-To header.',
    )
    cc: list[EmailAddress] | None = Field(
        ...,
        description='Parsed CC header addresses. Null if the email had no CC header.',
    )
    bcc: list[EmailAddress] | None = Field(
        ...,
        description='Parsed BCC header addresses. Null if the email had no BCC header. Note: BCC is only available for outgoing emails or when explicitly provided.',
    )
    in_reply_to: list[str] | None = Field(
        ...,
        description='In-Reply-To header values (Message-IDs of the email(s) being replied to). Null if the email had no In-Reply-To header. Per RFC 5322, this can contain multiple Message-IDs, though typically just one.',
        examples=[['<original-message-id@example.com>']],
    )
    references: list[str] | None = Field(
        ...,
        description='References header values (Message-IDs of the email thread). Null if the email had no References header.',
        examples=[['<msg1@example.com>', '<msg2@example.com>']],
    )
    attachments: list[WebhookAttachment] = Field(
        ...,
        description='List of attachments with metadata. Use  {@link  attachments_download_url }  to download the actual files.',
    )
    attachments_download_url: AnyUrl | None = Field(
        ...,
        description='HTTPS URL to download all attachments as a tar.gz archive. Null if the email had no attachments. URL expires - check the expiration before downloading.',
    )


class ParsedDataFailed(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    status: Literal['failed'] = Field(
        ..., description='Discriminant indicating parsing failed.'
    )
    error: ParsedError = Field(..., description='Details about why parsing failed.')
    body_text: None = Field(..., description='Always null when parsing fails.')
    body_html: None = Field(..., description='Always null when parsing fails.')
    reply_to: None = Field(..., description='Always null when parsing fails.')
    cc: None = Field(..., description='Always null when parsing fails.')
    bcc: None = Field(..., description='Always null when parsing fails.')
    in_reply_to: None = Field(..., description='Always null when parsing fails.')
    references: None = Field(..., description='Always null when parsing fails.')
    attachments: list[WebhookAttachment] = Field(
        ...,
        description='May contain partial attachment metadata even when parsing failed. Useful for debugging or recovering partial data.',
    )
    attachments_download_url: None = Field(
        ..., description='Always null when parsing fails.'
    )


class ForwardVerification(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    verdict: ForwardVerdict = Field(
        ..., description='Overall verdict on whether the forward is authentic.'
    )
    confidence: AuthConfidence = Field(
        ..., description='Confidence level for this verdict.'
    )
    dkim_verified: bool = Field(
        ...,
        description='Whether a valid DKIM signature was found that verifies the original sender.',
    )
    dkim_domain: str | None = Field(
        ...,
        description='Domain of the DKIM signature that verified the forward, if any.',
    )
    dmarc_policy: DmarcPolicy = Field(
        ..., description="DMARC policy of the original sender's domain."
    )


class ForwardResultAttachmentAnalyzed(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['attachment']
    attachment_tar_path: str = Field(
        ..., description='Path to the attachment in the attachments tar archive.'
    )
    attachment_filename: str | None = Field(
        ..., description='Original filename of the attachment, if available.'
    )
    analyzed: Literal[True] = Field(
        ..., description='Whether this attachment was analyzed.'
    )
    original_sender: ForwardOriginalSender | None = Field(
        ..., description='Original sender of the forwarded email, if extractable.'
    )
    verification: ForwardVerification = Field(
        ..., description='Verification result for the forwarded email.'
    )
    summary: str = Field(
        ..., description='Human-readable summary of the forward analysis.'
    )


class DkimSignature(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    domain: str = Field(
        ...,
        description="The domain that signed this DKIM signature (d= tag). This may differ from the From: domain (that's what alignment checks).",
    )
    selector: str | None = Field(
        None,
        description='The DKIM selector used to locate the public key (s= tag). Combined with the domain to form the DNS lookup: `selector._domainkey.domain`\n\nOptional in self-hosted environments where the milter may not provide selector info.',
    )
    result: DkimResult = Field(
        ..., description='Verification result for this specific signature.'
    )
    aligned: bool = Field(
        ...,
        description='Whether this signature\'s domain aligns with the From: domain (for DMARC).\n\nAlignment can be "strict" (exact match) or "relaxed" (organizational domain match). For example, if From: is `user@sub.example.com` and DKIM is signed by `example.com`:\n- Relaxed alignment: true (same organizational domain)\n- Strict alignment: false (not exact match)',
    )
    key_bits: int | None = Field(
        None,
        alias='keyBits',
        description="Key size in bits (e.g., 1024, 2048). Null if the key size couldn't be determined.\n\nOptional in self-hosted environments.",
        ge=1,
        le=16384,
    )
    algo: str | None = Field(
        None,
        description='Signing algorithm (e.g., "rsa-sha256", "ed25519-sha256").\n\nOptional in self-hosted environments.',
    )


class Content(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    raw: RawContent = Field(
        ...,
        description='Raw email in RFC 5322 format. May be inline (base64) or download-only depending on size.',
    )
    download: Download = Field(
        ...,
        description='Download information for the raw email. Always present, even if raw content is inline.',
    )


class ParsedData(RootModel[ParsedDataComplete | ParsedDataFailed]):
    root: ParsedDataComplete | ParsedDataFailed = Field(
        ..., description='Parsed email content - a discriminated union on `status`.'
    )


class ForwardResultInline(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['inline']
    original_sender: ForwardOriginalSender | None = Field(
        ..., description='Original sender of the forwarded email, if extractable.'
    )
    verification: ForwardVerification = Field(
        ..., description='Verification result for the forwarded email.'
    )
    summary: str = Field(
        ..., description='Human-readable summary of the forward analysis.'
    )


class EmailAuth(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    spf: SpfResult = Field(
        ...,
        description='SPF verification result.\n\nSPF checks if the sending IP is authorized by the envelope sender\'s domain. "pass" means the IP is authorized; "fail" means it\'s explicitly not allowed.',
    )
    dmarc: DmarcResult = Field(
        ...,
        description='DMARC verification result.\n\nDMARC passes if either SPF or DKIM passes AND aligns with the From: domain. "pass" means the email is authenticated according to the sender\'s policy.',
    )
    dmarc_policy: DmarcPolicy = Field(
        ...,
        alias='dmarcPolicy',
        description="DMARC policy from the sender's DNS record.\n\n- `reject`: Domain wants receivers to reject failing emails\n- `quarantine`: Domain wants failing emails marked as suspicious\n- `none`: Domain is monitoring only (no action requested)\n- `null`: No DMARC record found for this domain",
    )
    dmarc_from_domain: str | None = Field(
        ...,
        alias='dmarcFromDomain',
        description="The organizational domain used for DMARC lookups.\n\nFor example, if the From: address is `user@mail.example.com`, the DMARC lookup checks `_dmarc.mail.example.com`, then falls back to `_dmarc.example.com`. This field shows which domain's policy was used.",
    )
    dmarc_spf_aligned: bool | None = Field(
        None,
        alias='dmarcSpfAligned',
        description='Whether SPF aligned with the From: domain for DMARC purposes.\n\nTrue if the envelope sender domain matches the From: domain (per alignment mode). Optional in self-hosted environments.',
    )
    dmarc_dkim_aligned: bool | None = Field(
        None,
        alias='dmarcDkimAligned',
        description="Whether DKIM aligned with the From: domain for DMARC purposes.\n\nTrue if at least one DKIM signature's domain matches the From: domain. Optional in self-hosted environments.",
    )
    dmarc_spf_strict: bool | None = Field(
        ...,
        alias='dmarcSpfStrict',
        description='Whether DMARC SPF alignment mode is strict.\n\n- `true`: Strict alignment required (exact domain match)\n- `false`: Relaxed alignment allowed (organizational domain match)\n- `null`: No DMARC record found',
    )
    dmarc_dkim_strict: bool | None = Field(
        ...,
        alias='dmarcDkimStrict',
        description='Whether DMARC DKIM alignment mode is strict.\n\n- `true`: Strict alignment required (exact domain match)\n- `false`: Relaxed alignment allowed (organizational domain match)\n- `null`: No DMARC record found',
    )
    dkim_signatures: list[DkimSignature] = Field(
        ...,
        alias='dkimSignatures',
        description='All DKIM signatures found in the email with their verification results.\n\nMay be empty if no DKIM signatures were present.',
    )


class ForwardResult(
    RootModel[
        ForwardResultInline
        | ForwardResultAttachmentAnalyzed
        | ForwardResultAttachmentSkipped
    ]
):
    root: (
        ForwardResultInline
        | ForwardResultAttachmentAnalyzed
        | ForwardResultAttachmentSkipped
    ) = Field(
        ...,
        description="Result for a single forwarded email detected in the message.\n\nUse the `type` and `analyzed` fields to narrow the type:\n- `type: 'inline'` - Inline forward, always analyzed\n- `type: 'attachment'` + `analyzed: true` - Analyzed attachment\n- `type: 'attachment'` + `analyzed: false` - Skipped attachment",
    )


class ForwardAnalysis(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    detected: bool = Field(
        ..., description='Whether any forwards were detected in the email.'
    )
    results: list[ForwardResult] = Field(
        ..., description='Analysis results for each detected forward.'
    )
    attachments_found: int = Field(
        ..., description='Total number of .eml attachments found.', ge=0
    )
    attachments_analyzed: int = Field(
        ..., description='Number of .eml attachments that were analyzed.', ge=0
    )
    attachments_limit: int | None = Field(
        ...,
        description='Maximum number of attachments that will be analyzed, or null if unlimited.',
        ge=1,
    )


class EmailAnalysis(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    spamassassin: Spamassassin | None = Field(
        None, description='SpamAssassin analysis results.'
    )
    forward: ForwardAnalysis | None = Field(
        None, description='Forward detection and analysis results.'
    )


class Email(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: str = Field(
        ...,
        description='Unique email ID in Primitive. Use this ID when calling Primitive APIs to reference this email.',
    )
    received_at: str = Field(
        ...,
        description='ISO 8601 timestamp (UTC) when Primitive received the email.',
        examples=['2025-01-15T10:29:55.123Z'],
    )
    smtp: Smtp = Field(
        ...,
        description='SMTP envelope information. This is the "real" sender/recipient info from the SMTP transaction, which may differ from the headers (e.g., BCC recipients).',
    )
    headers: Headers = Field(
        ...,
        description='Parsed email headers. These are extracted from the email content, not the SMTP envelope.',
    )
    content: Content = Field(
        ..., description='Raw email content and download information.'
    )
    parsed: ParsedData = Field(
        ...,
        description='Parsed email content (body text, HTML, attachments). Check `status` to determine if parsing succeeded.',
    )
    analysis: EmailAnalysis = Field(
        ..., description='Email analysis and classification results.'
    )
    auth: EmailAuth = Field(
        ..., description='Email authentication results (SPF, DKIM, DMARC).'
    )


class EmailReceivedEvent(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: str = Field(
        ...,
        description='Unique delivery event ID.\n\nThis ID is stable across retries to the same endpoint - use it as your idempotency/dedupe key. Note that the same email delivered to different endpoints will have different event IDs.\n\nFormat: `evt_` prefix followed by a SHA-256 hash (64 hex characters). Example: `evt_a1b2c3d4e5f6...` (68 characters total)',
    )
    event: Literal['email.received'] = Field(
        ...,
        description='Event type identifier. Always `"email.received"` for this event type.',
    )
    version: WebhookVersion = Field(
        ...,
        description='API version in date format (YYYY-MM-DD). Use this to detect version mismatches between webhook and SDK.',
    )
    delivery: Delivery = Field(..., description='Metadata about this webhook delivery.')
    email: Email = Field(..., description='The email that triggered this event.')


class Model(RootModel[EmailReceivedEvent]):
    root: EmailReceivedEvent
